#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-io.github.milkshiift.GoofCord}"

declare -a FLAGS=()

if [[ $XDG_SESSION_TYPE == "wayland" && -z "$DISPLAY" ]]; then
    echo "Using Wayland"
    FLAGS+=(--enable-wayland-ime)
    FLAGS+=(--wayland-text-input-version=3)
    echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
fi

exec zypak-wrapper /app/bin/goofcord/goofcord "${FLAGS[@]}" "$@"
